from django.urls import re_path
from django.views.generic.base import RedirectView

from . import (
    view_adminphotos,
    view_boost,
    view_bow,
    view_bowrecap,
    view_cache_clear,
    view_distance,
    view_durelay,
    view_endurrace,
    view_endurrun,
    view_endurrunhome,
    view_endurrunstats,
    view_event,
    view_event_team,
    view_events,
    view_health,
    view_index,
    view_medals,
    view_member,
    view_members,
    view_multiwins,
    view_name,
    view_notify,
    view_photoupdate,
    view_race,
    view_race_slugs,
    view_recap,
    view_records,
    view_relay,
    view_series,
    view_stats,
    view_webhook,
)

urlpatterns = [
    re_path(r"^$", view_index.index, name="index"),
    re_path(r"^adminphotos", view_adminphotos.index, name="adminphotos"),
    re_path(
        r"^bowrecap/(?P<bow_slug>.*)/after/(?P<phase>.*)$",
        view_bowrecap.index,
        name="bowrecap",
    ),
    re_path(r"^bow/(?P<bow_slug>.*)/$", view_bow.index, name="bow"),
    re_path(r"^cache_clear", view_cache_clear.index, name="cache_clear"),
    re_path(r"^distance/(?P<distance_slug>.*)/$", view_distance.index, name="distance"),
    re_path(
        r"^distance",
        RedirectView.as_view(url="/distance/5-km/", permanent=False),
        name="distance_redirect",
    ),
    re_path(r"^durelay/(?P<year>[0-9]{4})/$", view_durelay.index, name="durelay"),
    re_path(r"^endurrace/(?P<year>.*)/$", view_endurrace.index, name="endurrace"),
    re_path(r"^endurrun/stats", view_endurrunstats.index, name="endurrunstats"),
    re_path(r"^endurrun/(?P<division>.*)/$", view_endurrun.index, name="endurrun"),
    re_path(r"^endurrun", view_endurrunhome.index, name="endurrunhome"),
    re_path(
        r"^event/(?P<year>[0-9]{4})/(?P<race_slug>.*)/(?P<distance_slug>.*)"
        "/team/(?P<team_category_slug>.*)/$",
        view_event_team.index,
        name="event_team",
    ),
    re_path(
        r"^event/(?P<year>[0-9]{4})/(?P<race_slug>.*)/(?P<distance_slug>.*)/$",
        view_event.index,
        name="event",
    ),
    re_path(r"^events", view_events.index, name="events"),
    re_path(r"^health", view_health.index, name="health"),
    re_path(r"^race_slugs", view_race_slugs.index, name="race_slugs"),
    re_path(
        r"^race/(?P<race_slug>.*)/(?P<distance_slug>.*)/$", view_race.index, name="race"
    ),
    re_path(
        r"^medals/(?P<year>[0-9]{4})/(?P<race_slug>.*)/(?P<distance_slug>.*)/$",
        view_medals.index,
        name="medals",
    ),
    re_path(r"^members", view_members.index, name="members"),
    re_path(r"^member/(?P<member_slug>.*)/$", view_member.index, name="member"),
    re_path(r"^multiwins", view_multiwins.index, name="multiwins"),
    re_path(r"^name", view_name.index, name="name"),
    re_path(r"^boost/(?P<year>.*)/$", view_boost.index, name="boost"),
    re_path(
        r"^boost/$",
        RedirectView.as_view(url="/boost/latest/", permanent=False),
        name="index",
    ),
    re_path(r"^notify", view_notify.index, name="notify"),
    re_path(r"^photoupdate", view_photoupdate.index, name="photoupdate"),
    re_path(
        r"^relay/(?P<year>.*)/(?P<race_slug>.*)/(?P<distance_slug>.*)/$",
        view_relay.index,
        name="relay",
    ),
    re_path(
        r"^recap/(?P<year>[0-9]{4})/(?P<race_slug>.*)/(?P<distance_slug>.*)/$",
        view_recap.index,
        name="recap",
    ),
    re_path(
        r"^records/(?P<race_slug>.*)/(?P<distance_slug>.*)/$",
        view_records.index,
        name="records",
    ),
    re_path(r"^series/(?P<series_slug>.*)/$", view_series.index, name="series"),
    re_path(r"^stats", view_stats.index, name="stats"),
    re_path(r"^webhook", view_webhook.index, name="webhook"),
]
