apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "racedb.fullname" . }}-celery"
  labels:
    {{- include "racedb.labels" . | nindent 4 }}
    app.kubernetes.io/task: celery
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "racedb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/task: celery
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "racedb.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/task: celery
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "racedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
            "/bin/sh",
            "-c",
            "celery -A racedb worker --concurrency={{ .Values.racedb.celeryWorkers }} -l info --pidfile=/tmp/celery.pid",
            ]
          env:
            - name: CHART
              value: {{ .Chart.Version }}
            - name: BUILD
              value: {{ .Values.image.tag }}
            - name: DJANGO_SETTINGS_MODULE
              value: racedb.settings.{{ .Values.racedb.settings }}
            - name: WEBHOST
              value: {{ .Values.ingress.host }}
          volumeMounts:
            {{- if eq .Values.racedb.settings "dev" }}
            - mountPath: /srv/racedb
              name: racedb
            {{- end }}
            - mountPath: /srv/racedb/racedb/secrets.py
              name: racedb-secrets
            - mountPath: /root/.flickr/oauth-tokens.sqlite
              name: racedb-flickr-oauth
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if eq .Values.racedb.settings "dev" }}
        - name: racedb
          hostPath:
            path: {{ .Values.racedb.devVolumePath }}
        {{- end }}
        - name: racedb-secrets
          hostPath:
            path: "{{ .Values.racedb.secretsVolumePath }}/secrets.py"
        - name: racedb-flickr-oauth
          hostPath:
            path: "{{ .Values.racedb.secretsVolumePath }}/flickr_oauth-tokens.sqlite"
