apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "racedb.fullname" . }}-web"
  labels:
    {{- include "racedb.labels" . | nindent 4 }}
    app.kubernetes.io/task: web
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.webReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "racedb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/task: web
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "racedb.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/task: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "racedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.racedb.settings "prod" }}
      initContainers:
        - name: "{{ .Chart.Name }}-collectstatic"
          command: [
            "/bin/sh",
            "-c",
            "./manage.py collectstatic --noinput",
            ]
          env:
            - name: CHART
              value: {{ .Chart.Version }}
            - name: BUILD
              value: {{ .Values.image.tag }}
            - name: DJANGO_SETTINGS_MODULE
              value: racedb.settings.{{ .Values.racedb.settings }}
            - name: WEBHOST
              value: {{ .Values.ingress.host }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - mountPath: /srv/racedb/racedb/secrets.py
              name: racedb-secrets
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
            "/bin/sh",
            "-c",
            {{- if eq .Values.racedb.settings "prod" }}
            "gunicorn racedb.wsgi --worker-class {{ .Values.racedb.workerClass }} --workers {{ .Values.racedb.workers}} --threads {{ .Values.racedb.threads }} -b 0.0.0.0:8000",
            {{- else }}
            "./manage.py runserver 0.0.0.0:8000",
            {{- end }}
            ]
          env:
            - name: CHART
              value: {{ .Chart.Version }}
            - name: BUILD
              value: {{ .Values.image.tag }}
            - name: DJANGO_SETTINGS_MODULE
              value: racedb.settings.{{ .Values.racedb.settings }}
            - name: WEBHOST
              value: {{ .Values.ingress.host }}
            - name: PROMETHEUS_METRICS_EXPORT_PORT
              value: "8001"
          volumeMounts:
            {{- if .Values.racedb.mountLocal }}
            - mountPath: /srv/racedb
              name: racedb
            {{- end }}
            - mountPath: /srv/racedb/racedb/secrets.py
              name: racedb-secrets
            - mountPath: /root/google_service_account.json
              name: racedb-google-service-account
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # {{- if eq .Values.racedb.settings "prod" }}
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.racedb.mountLocal }}
        - name: racedb
          hostPath:
            path: {{ .Values.racedb.devVolumePath }}
        {{- end }}
        - name: racedb-secrets
          hostPath:
            path: "{{ .Values.racedb.secretsVolumePath }}/secrets.py"
        - name: racedb-google-service-account
          hostPath:
            path: "{{ .Values.racedb.secretsVolumePath }}/google_service_account.json"

      {{- with .Values.nodeSelector }}
      strategy:
        rollingUpdate:
          maxUnavailable: 0
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
