{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.catchall.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: racedb-catchall
spec:
  entryPoints:
    - web
  routes:
    - match: {{ .Values.ingress.catchall.hostmatch}}
      priority: 1
      kind: Rule
      services:
        - name: "{{ include "racedb.fullname" . }}"
          port: {{ .Values.service.port}}
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "racedb.fullname" . }}-insecure"
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.ingress.host}}`) && !PathPrefix(`/v1`)"
      kind: Rule
      services:
        - name: "{{ include "racedb.fullname" . }}"
          port: {{ .Values.service.port}}
      middlewares:
        - name: "{{ include "racedb.fullname" . }}-redirect"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "racedb.fullname" . }}-secure"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ .Values.ingress.host}}`) && !PathPrefix(`/v1`)"
      kind: Rule
      services:
        - name: "{{ include "racedb.fullname" . }}"
          port: {{ .Values.service.port}}
  tls:
    certResolver: le
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "racedb.fullname" . }}-secure-api"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ .Values.ingress.apiHost}}`) && (PathPrefix(`/v1`) || PathPrefix(`/admin`))"
      kind: Rule
      services:
        - name: "{{ include "racedb.fullname" . }}"
          port: {{ .Values.service.port}}
  tls:
    certResolver: le
{{- end }}
