version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Django"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    commit-message:
      prefix: "chore(deps)"
      include: scope
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(docker)"
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(ci)"
      include: scope
