# The following variables need to be setup in GitLab under Settings | CI / CD | Variables
# GITLAB_CI_USER        (GitLab access token name)
# GITLAB_CI_TOKEN       (GitLab access token)
# AWS_ACCESS_KEY_ID     (AWS access key for S3)
# AWS_SECRET_ACCESS_KEY (AWS secret access key for S3)
# RACEDB_DB_BACKUP      (location of backup s3://...)
# PERSONAL_ACCESS_TOKEN (Gitlab personal access token)

image: docker:latest

stages:
  - build-test-push
  - tag

before_script:
  - docker login -u $GITLAB_CI_USER -p $GITLAB_CI_TOKEN $CI_REGISTRY

build-test-push:
  services:
    - docker:dind
    - mariadb:10.3.23
  variables:
    MYSQL_DATABASE: racedb
    MYSQL_USER: racedb
    MYSQL_PASSWORD: CHANGEME
    MYSQL_ROOT_PASSWORD: CHANGEME
  stage: build-test-push
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - /bin/ash deploy/minimal/deploy.sh
    - docker exec racedb_gunicorn ./manage.py test --settings=racedb.settings.min
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  retry: 2

tag:
  only:
    refs:
      - main
  stage: tag
  services:
    - docker:dind
  script:
    - export VERSION=`cat version.txt | xargs`
    - sh deploy/gitlab/tag.sh
