codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 70..100
  paths:
    - "racedbapp"
    - "*/racedbapp"
    - "*/*/racedbapp"

parsers:
  coverage:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
