version: '3'
networks:
  db:
  web:
services:
  db:
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_USER: racedb
      MYSQL_DATABASE: racedb
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
    image: mariadb:10.3
    networks:
      - db
    volumes:
       - /srv/racedb_db:/docker-entrypoint-initdb.d
       - /srv/racedb_secrets:/run/secrets
  gunicorn:
    command: /bin/bash -c "./manage.py collectstatic --noinput; gunicorn racedb.wsgi -b 0.0.0.0:8000 --reload"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    image: racedb-gunicorn
    networks:
      - db
      - web
    volumes:
      - /srv/racedb:/srv/racedb
      - /srv/racedb_static:/static
      - /srv/racedb_secrets:/run/secrets
  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx:1.15-alpine
    networks:
      - web 
    ports:
      - "8010:80"
    volumes:
      - /srv/racedb_nginx:/etc/nginx/conf.d
      - /srv/racedb_static:/static
