version: '3'
networks:
  db:
  web:
services:
  db:
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_USER: racedb
      MYSQL_DATABASE: racedb
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
    image: mariadb:10.3
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_db"
    networks:
      - db
    volumes:
       - /srv/racedb_db:/docker-entrypoint-initdb.d
       - /srv/racedb_secrets:/run/secrets
  gunicorn:
    command: "/bin/sh -c 'gunicorn racedb.wsgi -b 0.0.0.0:8000 --reload --reload-extra-file .restart'"
    image: racedb-gunicorn
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_gunicorn"
    networks:
      - db
      - web
    volumes:
      - /srv/racedb:/srv/racedb
      - /srv/racedb_static:/static
      - /srv/racedb_secrets:/run/secrets
  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx:1.15-alpine
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_nginx"
    networks:
      - web 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/racedb_nginx:/etc/nginx/conf.d
      - /srv/racedb_certbot/conf:/etc/letsencrypt
      - /srv/racedb_certbot/www:/var/www/certbot
      - /srv/racedb_static:/static
  redis:
    image: "redis:alpine"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_redis"
    networks:
      - web
  celery:
    image: racedb-celery
    command: /bin/sh -c 'watchmedo auto-restart -p "*.restart" -- celery -A racedb worker -l info --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_celery"
    volumes:
      - /srv/racedb:/srv/racedb
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
    networks:
      - db
      - web
  beat:
    image: racedb-celery
    command: /bin/sh -c 'watchmedo auto-restart -p ".restart" -- celery -A racedb beat -l info --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_beat"
    volumes:
      - /srv/racedb:/srv/racedb
    networks:
      - db
      - web
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_certbot"
    volumes:
      - /srv/racedb_certbot/conf:/etc/letsencrypt
      - /srv/racedb_certbot/www:/var/www/certbot
