#########################################################################
## https://github.com/kamaln7/ansible-swapfile/blob/master/tasks/main.yml
#########################################################################

- name: write swapfile (slow)
  command: |
    {% if swapfile_use_dd %}
    dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size_mb }} creates={{ swapfile_location }}
    {% else %}
    fallocate -l {{ swapfile_size_mb }}MB {{ swapfile_location }} creates={{ swapfile_location }}
    {% endif %}
  register: write_swapfile
  when: swapfile_size_mb != false
  tags:
  - base
  - swap

- name: set swapfile permissions
  file: path={{ swapfile_location }} mode=600
  when: swapfile_size_mb != false
  tags:
  - base
  - swap

- name: create swapfile
  command: mkswap {{ swapfile_location }}
  register: create_swapfile
  when: swapfile_size_mb != false and write_swapfile.changed
  tags:
  - base
  - swap

- name: enable swapfile
  command: swapon {{ swapfile_location }}
  when: swapfile_size_mb != false and create_swapfile.changed
  tags:
  - base
  - swap

- name: add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
  when: swapfile_size_mb != false
  tags:
  - base
  - swap

- name: configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  when: swapfile_swappiness != false
  tags:
  - base
  - swap

- name: configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  when: swapfile_vfs_cache_pressure != false
  tags:
  - base
  - swap

