from .base import *

DEBUG = False

AWS_ACCESS_KEY_ID = secrets.RACEDB_STATIC_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = secrets.RACEDB_STATIC_AWS_SECRET_ACCESS_KEY
AWS_S3_BUCKET_NAME_STATIC = "racedb-static"
AWS_S3_MAX_AGE_SECONDS = "315360000"
STATICFILES_STORAGE = "django_s3_storage.storage.ManifestStaticS3Storage"
