---
- name: add http and https to firewalld
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - https
  when: ansible_hostname != "paris"
  tags:
    - django_docker
    - firewalld
