# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('ismasters', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('km', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Distance')),
            ],
            options={
                'ordering': ('-date', '-distance__km'),
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=50)),
                ('place', models.IntegerField()),
                ('bib', models.CharField(blank=True, max_length=6)),
                ('chiptime', models.DurationField(null=True)),
                ('guntime', models.DurationField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
            options={
                'ordering': ('place',),
            },
        ),
        migrations.CreateModel(
            name='Teamcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teamresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_place', models.IntegerField()),
                ('team_name', models.CharField(max_length=64)),
                ('athlete_team_place', models.IntegerField()),
                ('athlete_time', models.DurationField()),
                ('athlete_name', models.CharField(max_length=64)),
                ('counts', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
                ('team_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Teamcategory')),
            ],
            options={
                'ordering': ('event', 'team_category', 'team_place', 'athlete_team_place'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Race'),
        ),
        migrations.AlterUniqueTogether(
            name='teamresult',
            unique_together=set([('event', 'team_category', 'team_name', 'athlete_team_place')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('event', 'place')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('race', 'distance', 'date')]),
        ),
    ]
