# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='prename',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
