# Generated by Django 1.9 on 2016-02-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0002_distance_prename'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='prename',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='shortname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
