# Generated by Django 1.9 on 2016-02-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0003_auto_20160202_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='blurb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
