# Generated by Django 1.9 on 2016-02-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0005_teamresult_estimated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcategory',
            options={'ordering': ('sortorder',)},
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='sortorder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
