# Generated by Django 1.9 on 2016-03-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0007_bow_bowathlete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bowathlete',
            unique_together={('bow', 'name')},
        ),
    ]
