# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0007_bow_bowathlete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bowathlete',
            unique_together=set([('bow', 'name')]),
        ),
    ]
