# Generated by Django 1.9 on 2016-04-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0008_auto_20160317_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endurraceresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('athlete', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=50)),
                ('bib', models.CharField(blank=True, max_length=6)),
                ('guntime', models.DurationField()),
                ('fivektime', models.DurationField()),
                ('eightktime', models.DurationField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='endurraceresult',
            unique_together={('year', 'athlete')},
        ),
    ]
