# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0010_prime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prime',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
