# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0012_remove_prime_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
