# Generated by Django 1.9.5 on 2016-05-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0013_prime_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheelchairresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=50)),
                ('place', models.IntegerField()),
                ('bib', models.CharField(blank=True, max_length=6)),
                ('chiptime', models.DurationField(null=True)),
                ('guntime', models.DurationField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
            options={
                'ordering': ('place',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='wheelchairresult',
            unique_together={('event', 'place')},
        ),
    ]
