# Generated by Django 1.9.5 on 2016-07-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0015_result_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('split_num', models.IntegerField()),
                ('split_time', models.DurationField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='split',
            unique_together={('event', 'place', 'split_num')},
        ),
    ]
