# Generated by Django 1.9.5 on 2016-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0016_auto_20160713_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='endurathlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('division', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='endurteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('ismasters', models.BooleanField(default=False)),
                ('st1', models.CharField(max_length=100)),
                ('st2', models.CharField(max_length=100)),
                ('st3', models.CharField(max_length=100)),
                ('st4', models.CharField(max_length=100)),
                ('st5', models.CharField(max_length=100)),
                ('st6', models.CharField(max_length=100)),
                ('st7', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='endurteam',
            unique_together={('year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='endurathlete',
            unique_together={('year', 'division', 'name')},
        ),
    ]
