# Generated by Django 1.9.5 on 2016-07-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0017_auto_20160713_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
