# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0021_auto_20160916_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resultsurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
