# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0022_event_resultsurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('joindate', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('photourl', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
