# Generated by Django 1.10.3 on 2016-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0023_rwmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwmember',
            name='altname',
            field=models.CharField(default='', help_text='Optional, e.g. maiden name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rwmember',
            name='slug',
            field=models.SlugField(help_text='https://blog.tersmitten.nl/slugify/', unique=True),
        ),
    ]
