# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0024_auto_20161113_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwmembercorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('include', 'include'), ('exclude', 'exclude')], max_length=7)),
                ('bib', models.CharField(blank=True, max_length=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='rwmember',
            name='altname',
            field=models.CharField(blank=True, help_text='Optional, e.g. maiden name', max_length=64),
        ),
        migrations.AddField(
            model_name='rwmembercorrection',
            name='rwmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Rwmember'),
        ),
    ]
