# Generated by Django 1.10.3 on 2016-11-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0025_auto_20161113_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rwmember',
            options={'ordering': ('name',)},
        ),
    ]
