# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0026_auto_20161113_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rwmember',
            options={},
        ),
    ]
