# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0027_auto_20161113_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmembercorrection',
            name='correction_type',
            field=models.CharField(choices=[('exclude', 'exclude'), ('include', 'include')], max_length=7),
        ),
    ]
