# Generated by Django 1.10.3 on 2016-12-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0030_auto_20161120_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='showrecord',
            field=models.BooleanField(default=False),
        ),
    ]
