# Generated by Django 1.10.5 on 2017-03-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0031_distance_showrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phototag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
        ),
    ]
