# Generated by Django 1.10.5 on 2017-03-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0032_phototag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flickrsetid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
