# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0035_auto_20170313_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwmember',
            name='hasphotos',
            field=models.BooleanField(default=False),
        ),
    ]
