# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0036_rwmember_hasphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='hasphotos',
            field=models.BooleanField(default=False, help_text='Automatically set by system'),
        ),
    ]
