# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0038_result_rwmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Just the video id, not the whole URL', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_offset_seconds',
            field=models.IntegerField(blank=True, default=None, help_text='Elapsed race time (in seconds) at start of video', null=True),
        ),
    ]
