# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0040_auto_20170523_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
