# Generated by Django 1.11.5 on 2017-10-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0041_auto_20170813_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phototagbackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrw_photo_id', models.CharField(max_length=64, unique=True)),
                ('flickr_photo_id', models.IntegerField(db_index=True)),
                ('flickr_set_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=256)),
                ('date_time_original', models.CharField(max_length=32)),
                ('tags', models.TextField()),
            ],
        ),
    ]
