# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0042_phototagbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototagbackup',
            name='flickr_photo_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='phototagbackup',
            name='flickr_set_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
