# Generated by Django 1.11.5 on 2017-11-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0043_auto_20171026_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phototagbackup',
        ),
    ]
