# Generated by Django 1.11.7 on 2017-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0046_auto_20171111_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwmembertags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='rwmember',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='racedbapp.Rwmembertags'),
        ),
    ]
