# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0047_auto_20171111_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rwmembertags',
            new_name='Rwmembertag',
        ),
    ]
