# Generated by Django 1.11.7 on 2017-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0048_auto_20171111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='catergory_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='gender_place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
