# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0050_auto_20171201_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelchairresult',
            options={},
        ),
        migrations.AddField(
            model_name='result',
            name='isrwpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='wheelchairresult',
            unique_together=set([]),
        ),
    ]
