# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0051_auto_20171204_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='tags',
            field=models.ManyToManyField(blank=True, to='racedbapp.Rwmembertag'),
        ),
    ]
