# Generated by Django 1.11.7 on 2017-12-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0053_auto_20171206_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='joindate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
