# Generated by Django 1.11.7 on 2017-12-24 01:52

from django.db import migrations, models
import racedbapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0054_auto_20171223_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='tags',
            field=models.ManyToManyField(blank=True, default=racedbapp.models.Rwmember.membertag_defaults, to='racedbapp.Rwmembertag'),
        ),
    ]
