# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0055_auto_20171223_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwmembertag',
            name='auto_select',
            field=models.BooleanField(default=False),
        ),
    ]
