# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0056_rwmembertag_auto_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('relay_team', models.CharField(max_length=128)),
                ('relay_team_place', models.IntegerField()),
                ('relay_team_time', models.DurationField(null=True)),
                ('relay_leg', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
        ),
    ]
