# Generated by Django 2.0.4 on 2018-05-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0057_relay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Durelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_place', models.IntegerField()),
                ('team_name', models.CharField(max_length=128)),
                ('team_time', models.DurationField(null=True)),
                ('run1_athlete', models.CharField(max_length=128)),
                ('run1_time', models.DurationField(null=True)),
                ('t1_time', models.DurationField(null=True)),
                ('bike_athlete', models.CharField(max_length=128)),
                ('bike_time', models.DurationField(null=True)),
                ('t2_time', models.DurationField(null=True)),
                ('run2_athlete', models.CharField(max_length=128)),
                ('run2_time', models.DurationField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racedbapp.Event')),
            ],
        ),
    ]
