# Generated by Django 2.0.4 on 2018-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0058_durelay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='durelay',
            name='event',
        ),
        migrations.AddField(
            model_name='durelay',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
