# Generated by Django 2.0.4 on 2018-05-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0059_auto_20180512_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='durelay',
            name='t1_time',
        ),
        migrations.RemoveField(
            model_name='durelay',
            name='t2_time',
        ),
    ]
