# Generated by Django 2.0.5 on 2018-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0060_auto_20180512_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_duration_seconds',
            field=models.IntegerField(blank=True, default=None, help_text='OPTIONAL: Total duration (in seconds) of YouTube video. This is only required if the video cuts off early.', null=True),
        ),
    ]
