# Generated by Django 2.1.7 on 2019-03-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("racedbapp", "0061_event_youtube_duration_seconds")]

    operations = [
        migrations.RemoveField(model_name="race", name="prename"),
        migrations.AlterField(
            model_name="result",
            name="isrwpb",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
