# Generated by Django 2.1.7 on 2019-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0062_auto_20190306_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
