# Generated by Django 2.2.9 on 2020-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0063_auto_20190413_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='awards',
            field=models.CharField(choices=[('none', 'none'), ('standard', 'standard')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='endurteam',
            name='year',
            field=models.IntegerField(help_text='Teams should not be added or modified in the admin, only deleted if necessary. They get created and updated automatically from results.'),
        ),
    ]
