# Generated by Django 2.2.9 on 2020-02-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0064_auto_20200206_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='awards',
            new_name='medals',
        ),
    ]
