# Generated by Django 4.0.7 on 2022-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("racedbapp", "0066_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("name", models.CharField(max_length=100)),
                ("website_url", models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="relay",
            name="place",
            field=models.IntegerField(
                help_text="Overall place this person finished in the individual event"
            ),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_leg",
            field=models.IntegerField(
                help_text="Relay leg for this individual (e.g. 1, 2)"
            ),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_team",
            field=models.CharField(help_text="Relay team name", max_length=128),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_team_place",
            field=models.IntegerField(help_text="Place the relay team finished"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_team_time",
            field=models.DurationField(
                help_text="Total time for the relay team", null=True
            ),
        ),
    ]
