# Generated by Django 4.0.7 on 2022-08-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("racedbapp", "0067_timer_alter_relay_place_alter_relay_relay_leg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="racedbapp.timer",
            ),
        ),
    ]
