# Generated by Django 4.0.7 on 2022-08-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("racedbapp", "0068_event_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="racedbapp.timer",
            ),
        ),
    ]
