# Generated by Django 4.1.4 on 2023-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("racedbapp", "0070_alter_event_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bowathlete",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("NB", "Nonbinary")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="endurathlete",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("NB", "Nonbinary")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="endurraceresult",
            name="gender",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="endurteam",
            name="gender",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="prime",
            name="gender",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="result",
            name="gender",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="rwmember",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("NB", "Nonbinary")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="wheelchairresult",
            name="gender",
            field=models.CharField(max_length=2),
        ),
    ]
