# Generated by Django 4.2.1 on 2023-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0071_alter_bowathlete_gender_alter_endurathlete_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Nonbinary')], max_length=2),
        ),
    ]
