# Generated by Django 5.0.7 on 2025-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0072_alter_rwmember_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='medals',
            field=models.CharField(choices=[('none', 'none'), ('standard', 'standard'), ('classic-5oa', 'classic-5oa')], default='none', max_length=32),
        ),
    ]
