# Generated by Django 5.0.14 on 2025-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0073_alter_event_medals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwmember',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
