# Generated by Django 5.2.4 on 2025-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0075_result_racedbapp_r_rwmembe_96dac5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_logo_url',
            field=models.URLField(blank=True, help_text='Override default race logo with a custom one for this event', max_length=500, null=True),
        ),
    ]
