# Generated by Django 5.2.4 on 2025-07-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0076_event_custom_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='sequel',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional: Attach a Sequel instance to this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='racedbapp.sequel'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('race', 'distance', 'date', 'sequel')},
        ),
    ]
