# Generated by Django 5.2.4 on 2025-07-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0077_sequel_alter_event_unique_together_event_sequel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
