# Generated by Django 6.0.6 on 2026-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0078_alter_sequel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='age_grade_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
