# Generated by Django 6.0.7 on 2026-10-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racedbapp', '0079_series_age_grade_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='prename',
        ),
    ]
