apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  labels:
    app: traefik
spec:
  storageClassName: manual
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/traefik"