apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  selector:
    matchLabels:
      app: traefik
