fullnameOverride: racedbdev
racedb:
  settings: dev
  secretsVolumePath: /srv/racedb_secrets_dev
  storage: local
ingress:
  catchall:
    enabled: false
  host: racedb.runwaterloo.com
  apiHost: racedb-api.runwaterloo.com
