version: '3.4'
networks:
  db:
  web:
services:
  db:
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_USER: racedb
      MYSQL_DATABASE: racedb
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
    image: mariadb:10.3.18
    networks:
      - db
    volumes:
       - /srv/racedb_db:/docker-entrypoint-initdb.d
       - /srv/racedb_secrets:/run/secrets
  gunicorn:
    command: /bin/sh -c "./manage.py collectstatic --noinput; gunicorn racedb.wsgi -b 0.0.0.0:8000"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
      BUILD: $BUILD
    image: racedb:latest
    networks:
      - db
      - web
    volumes:
      - /srv/racedb_static:/static
      - /srv/racedb_secrets:/run/secrets
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx:1.17-alpine
    networks:
      - web 
    ports:
      - "8010:80"
    volumes:
      - /srv/racedb_nginx:/etc/nginx/conf.d
      - /srv/racedb_certbot/conf:/etc/letsencrypt
      - /srv/racedb_certbot/www:/var/www/certbot
      - /srv/racedb_static:/static
  redis:
    image: redis:5.0.6-alpine
    networks:
      - web
  celery:
    image: racedb:latest
    command: /bin/sh -c 'celery -A racedb worker -l info --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
    networks:
      - db
      - web
  beat:
    image: racedb:latest
    command: /bin/sh -c 'celery -A racedb beat -l info --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    networks:
      - db
      - web
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
