version: '3.4'
networks:
  db:
  web:
services:
  db:
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_USER: racedb
      MYSQL_DATABASE: racedb
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
    image: mariadb:10.4.8
    networks:
      - db
    volumes:
       - /srv/racedb_db:/docker-entrypoint-initdb.d
       - /srv/racedb_secrets:/run/secrets
  django:
    command: /bin/sh -c "./manage.py runserver --settings=racedb.settings.dev 0.0.0.0:8000"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
      BUILD: $BUILD
    image: racedb:latest
    networks:
      - db
      - traefik_default
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.services.racedb.loadbalancer.server.port=8000
      - traefik.http.routers.racedb.entrypoints=web-secure
      - traefik.http.routers.racedb.rule=Host(`racedb.scrw.ca`)
      - traefik.http.routers.racedb.tls=true
      - traefik.http.routers.racedb.tls.certresolver=default
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
  redis:
    image: redis:5.0.6-alpine
    networks:
      - web
  celery:
    image: racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.dev" celery -A racedb worker -l info --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
    networks:
      - db
      - web
  beat:
    image: racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.dev" celery -A racedb beat -l info --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    networks:
      - db
      - web
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
      - /srv/racedb_secrets/app_secrets.py:/srv/racedb/racedbapp/secrets.py
networks:
  traefik_default:
    external: true
  web:
  db:
