version: '3.4'
services:
  django:
    command: /bin/sh -c "./manage.py runserver --settings=racedb.settings.dev 0.0.0.0:8000"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
      BUILD: $BUILD
    image: racedb:latest
    networks:
      - mariadb_default
      - traefik_default
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.services.racedb.loadbalancer.server.port=8000
      - traefik.http.routers.racedb.entrypoints=web-secure
      - traefik.http.routers.racedb.rule=Host(`racedb.scrw.ca`)
      - traefik.http.routers.racedb.tls=true
      - traefik.http.routers.racedb.tls.certresolver=default
      # redirect http
      - traefik.http.middlewares.racedb-redirect.redirectscheme.scheme=https
      - traefik.http.routers.racedb-insecure.entrypoints=web
      - traefik.http.routers.racedb-insecure.rule=Host(`racedb.scrw.ca`)
      - traefik.http.routers.racedb-insecure.middlewares=racedb-redirect
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
  redis:
    image: redis:5.0.9-alpine
    networks:
      - web
  celery:
    image: racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.dev" celery -A racedb worker -l INFO --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
    networks:
      - mariadb_default
      - web
  beat:
    image: racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.dev" celery -A racedb beat -l INFO --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    networks:
      - mariadb_default
      - web
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
networks:
  traefik_default:
    external: true
  mariadb_default:
    external: true
  web:
