- name: restart crond
  service: name=crond state=restarted

- name: restart network
  service: name=network state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: restart sshd
  service: name=sshd state=restarted
