version: '3.4'
networks:
  web:
  traefik_default:
    external: true
services:
  gunicorn:
    command: /bin/sh -c './manage.py collectstatic --noinput --settings=racedb.settings.prod; gunicorn --env DJANGO_SETTINGS_MODULE=racedb.settings.prod racedb.wsgi -b 0.0.0.0:8000'
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      BUILD: $BUILD
    healthcheck:
      test: curl --fail -s http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    image: registry.gitlab.com/sl70176/racedb:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.services.racedb.loadbalancer.server.port=8000
      - traefik.http.routers.racedb.entrypoints=web-secure
      - traefik.http.routers.racedb.rule=Host(`results.runwaterloo.com`)
      - traefik.http.routers.racedb.tls=true
      - traefik.http.routers.racedb.tls.certresolver=default
      # accept wilcard, do not redirect
      - traefik.http.routers.racedb-wildcard.rule=hostregexp(`{host:.+}`)
      # redirect http for results.runwaterloo.com
      - traefik.http.middlewares.racedb-redirect.redirectscheme.scheme=https
      - traefik.http.routers.racedb-insecure.entrypoints=web
      - traefik.http.routers.racedb-insecure.rule=Host(`results.runwaterloo.com`)
      - traefik.http.routers.racedb-insecure.middlewares=racedb-redirect
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_gunicorn"
    networks:
      - web
      - traefik_default
    volumes:
      - /srv/racedb_secrets:/run/secrets
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
  redis:
    image: redis:5.0.9-alpine
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_redis"
    networks:
      - web
  celery:
    image: registry.gitlab.com/sl70176/racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.prod" celery -A racedb worker -l info --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_celery"
    volumes:
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
    networks:
      - web
  beat:
    image: registry.gitlab.com/sl70176/racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.prod" celery -A racedb beat -l info --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_beat"
    networks:
      - web
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
