version: '3.4'
networks:
  web:
services:
  gunicorn:
    command: /bin/sh -c './manage.py collectstatic --noinput --settings=racedb.settings.prod; gunicorn --env DJANGO_SETTINGS_MODULE=racedb.settings.prod racedb.wsgi -b 0.0.0.0:8000'
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      BUILD: $BUILD
    healthcheck:
      test: curl --fail -s http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    image: registry.gitlab.com/sl70176/racedb:latest
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_gunicorn"
    networks:
      - web
    volumes:
      - /srv/racedb_secrets:/run/secrets
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx:1.17-alpine
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_nginx"
    networks:
      - web 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/racedb_nginx:/etc/nginx/conf.d
      - /srv/racedb_certbot/conf:/etc/letsencrypt
      - /srv/racedb_certbot/www:/var/www/certbot
  redis:
    image: redis:5.0.7-alpine
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_redis"
    networks:
      - web
  celery:
    image: registry.gitlab.com/sl70176/racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.prod" celery -A racedb worker -l info --pidfile=/tmp/celery.pid'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_celery"
    volumes:
      - /srv/racedb_secrets/flickr_oauth-tokens.sqlite:/root/.flickr/oauth-tokens.sqlite
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
    networks:
      - web
  beat:
    image: registry.gitlab.com/sl70176/racedb:latest
    command: /bin/sh -c 'DJANGO_SETTINGS_MODULE="racedb.settings.prod" celery -A racedb beat -l info --pidfile=/tmp/celery.pid -s /tmp/celerybeat-schedule'
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_beat"
    networks:
      - web
    volumes:
      - /srv/racedb_secrets/secrets.py:/srv/racedb/racedb/secrets.py
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot:v0.40.1
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "racedb"
        awslogs-stream: "racedb_certbot"
    volumes:
      - /srv/racedb_certbot/conf:/etc/letsencrypt
      - /srv/racedb_certbot/www:/var/www/certbot
