name: Build and Push Docker Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set short SHA variable
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/racedb:${{ env.SHORT_SHA }}

      - name: Set and show version number
        if: github.ref_name == 'releases'
        run: |
          RUN_NUMBER=${{ github.run_number }}
          MAJOR=$(((RUN_NUMBER / 1000) + 3))
          MINOR=$(TZ=America/Toronto date +'%y%m%d')
          PATCH=$((RUN_NUMBER % 1000))
          VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "Calculated VERSION: $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Tag and push Docker image with VERSION
        if: env.VERSION
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/racedb:${{ env.SHORT_SHA }} ghcr.io/${{ github.repository_owner }}/racedb:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/racedb:${{ env.VERSION }}

      - name: Save VERSION as artifact
        if: env.VERSION
        run: echo "${VERSION}" > version.txt

      - name: Upload VERSION artifact
        if: env.VERSION
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
