name: Build and Push Docker Image

permissions:
  packages: write

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.head_commit.message, '[push dev]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set short SHA variable
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/racedb:${{ env.SHORT_SHA }}
