name: "Validate PR title"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  semantic-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          types: |
            feat
            fix
            chore
            docs
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
