name: Pre-commit autoupdate

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(pre-commit): autoupdate hooks"
          branch: pre-commit-autoupdate
          title: "chore(pre-commit): autoupdate hooks"
          body: "This PR updates pre-commit hooks via `pre-commit autoupdate`.\n\n[skip build]"
          delete-branch: true
