name: Registry Cleanup

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 03:00 UTC
  workflow_dispatch:
  push:

jobs:
  cleanup:
    name: Cleanup Old Container Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete old images from GitHub Container Registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: racedb
          package-type: container
          min-versions-to-keep: 45
          delete-only-untagged-versions: false
