name: Tag Commit

on:
  workflow_run:
    workflows: ["Unit Tests", "Build and Push Docker Image"]
    types:
      - completed

jobs:
  tag-commit:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download version artifact
        id: download_version
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: version
          run-id: ${{ github.event.workflow_run.id }}

      - name: Check if version exists
        id: check_version
        run: |
          if [ ! -f version.txt ] || [ ! -s version.txt ]; then
            echo "No version found, skipping tag."
            exit 0
          fi

      - name: Read version
        if: steps.check_version.outcome == 'success'
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout code
        if: steps.check_version.outcome == 'success'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Tag commit
        if: steps.check_version.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
