name: Unit Tests

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    name: Execute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Prepare secrets file
        run: cp racedb/secrets.py.sample racedb/secrets.py

      - name: Remove mysqlclient from requirements.txt
        run: sed -i '/^mysqlclient/d' requirements/requirements.txt

      - name: Install test requirements
        run: pip install --root-user-action=ignore -r requirements/requirements-test.txt

      - name: Run tests with coverage
        id: run-tests-with-coverage
        run: pytest --junitxml=report.xml --cov=racedbapp --cov-report=xml --cov-branch
        # continue-on-error: true

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Test results
          path: report.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Fail if tests failed
      #   if: steps.run-tests-with-coverage.outcome == 'failure'
      #   run: exit 1
