name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.13.2-alpine3.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install git for test reporter
        run: apk add --no-cache git

      - name: Prepare secrets file
        run: cp racedb/secrets.py.sample racedb/secrets.py

      - name: Remove mysqlclient from requirements.txt
        run: sed -i '/^mysqlclient/d' requirements/requirements.txt

      - name: Install test requirements
        run: pip install --root-user-action=ignore -r requirements/requirements-test.txt

      - name: Run tests with coverage
        run: pytest --junitxml=report.xml --cov=racedbapp --cov-report=term --cov-branch

      - name: Upload test results (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Publish test results to PR
        if: github.event_name == 'pull_request'
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: report.xml
          reporter: java-junit
