name: Unit Tests

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Prepare secrets file
        run: cp racedb/secrets.py.sample racedb/secrets.py

      - name: Remove mysqlclient from requirements.txt
        run: sed -i '/^mysqlclient/d' requirements/requirements.txt

      - name: Install test requirements
        run: pip install --root-user-action=ignore -r requirements/requirements-test.txt

      - name: Run tests with coverage
        run: pytest --cov=racedbapp --cov-report=xml --cov-branch

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
