name: Unit Tests

permissions:
  checks: write
  contents: read

on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Prepare secrets file
        run: cp racedb/secrets.py.sample racedb/secrets.py

      - name: Remove mysqlclient from requirements.txt
        run: sed -i '/^mysqlclient/d' requirements/requirements.txt

      - name: Install test requirements
        run: pip install --root-user-action=ignore -r requirements/requirements-test.txt

      - name: Run tests with coverage
        run: pytest --junitxml=report.xml --cov=racedbapp --cov-report=term --cov-branch

      - name: Upload test results (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Test report
          path: report.xml
          reporter: java-junit
          check_run_annotations: all tests
